run: DijkstraPath.class 
	java DijkstraPath graph.txt a f

DijkstraPath.class: DijkstraPath.java BinaryHeapNode.java Edge.java EmptyHeapNode.java HeapNode.java HeapTree.java Moore.java Node.java Pair.java 
	javac DijkstraPath.java

