A Jupyter notebook consists of two different types of cells:
- *Code cells* contain Python code, while
- *Markdown cells* are used to write comments.  

The current cell is a *markdown cell*, the next cell is a *code cell*.
This code cell is only needed to format this notebook.

In [1]:
from IPython.core.display import HTML
with open('../style.css', 'r') as file:
    css = file.read()
HTML(css)

# An Introduction to *Python*

Let us begin by checking the version of our Python interpreter.
The package `sys` contains the variable `version` that stores this information.

In [2]:
import sys
sys.version

'3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ]'

This notebook gives a short introduction to *Python*.  We will just present the basics.
More interesting features will be presented later.

## Evaluating expressions

As Python is an interactive language, expressions can be evaluated directly.  In a *Jupyter* 
notebook we just have to type <tt>Ctrl-Enter</tt> in the cell containing the expression.  Instead
of <tt>Ctrl-Enter</tt> we can also use <tt>Shift-Enter</tt>.

In [3]:
1 + 2

3

In *Python*, the precision of integers is not bounded.  Hence, the following expression does **not** cause
an <a href="https://en.wikipedia.org/wiki/Integer_overflow">integer overflow</a>.

In [4]:
1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * 10 * 11 * 12 * 13 * 14 * 15 * 16 * 17 * 18 * 19 * 20 * 21 * 22

1124000727777607680000

Here is another example that show that *Python* is able to compute with huge numbers.  
In this example, the operator `**` is used for exponentiation, i.e. the expression
```
    7 ** 125
```
is interpreted as $7^{125}$.

In [7]:
7 ** 125

4337654948097993282537354757263188251697832994620405101744893017744569432720994168089672192211758909320807

In order to print numbers or strings, we can use the function `print`.  This function can print objects of any type.  In the following example, this function prints a *string*.  In *Python* any character sequence 
enclosed in single quotes is interpreted as a *string*.

In [8]:
print('Hello, World!')

Hello, World!


The last expression in every notebook cell is automatically printed.  Therefore, printing `'Hello, World!'` can also be done by just executing the following cell.

In [9]:
'Hello, World!'

'Hello, World!'

If we want to supress the last expression from being printed, we can end the expression with a semicolon:

In [10]:
'Hello, World!';

Instead of using single quotes we can also use double quotes as seen in the next example.  However, the convention is to use single quotes, unless the string itself contains a single quote.

In [11]:
"Hello, World!"

'Hello, World!'

In [12]:
"This can't be the case!"

"This can't be the case!"

The function <tt>print</tt> accepts any number of arguments.  For example, to print the string "36 * 37 / 2 = " followed by the value of the expression $36 \cdot 37 / 2$ we can use the following <tt>print</tt> statement:

In [13]:
print('36 * 37 / 2 =', 36 * 37 // 2)

36 * 37 / 2 = 666


In [16]:
type(666)

int

In the expression "<tt>36 \* 37 // 2</tt>" we have used the operator "<tt>//</tt>" in order to enforce *integer division*, which is also known as *Euclidean division*.  If we had used the operator "<tt>/</tt>" instead, *Python* would have used *floating point division* and therefore it would have printed the floating point number <tt>666.0</tt> instead of the integer <tt>666<tt>. 

In [17]:
type(666.0)

float

In [14]:
print('36 * 37 / 2 =', 36 * 37 / 2)

36 * 37 / 2 = 666.0


The next cell demonstrates [Euclidean division](https://en.wikipedia.org/wiki/Euclidean_division).

In [18]:
7 // 3

2

The *remainder* that is left in an integer division is computed with the operator `%`. 

In [19]:
7 % 3

1

The result of a computation can be stored in a *variable*.  For example, to store the quotient resulting from dividing $7$ by $3$ into the variable with name `q` and to store the remainder into a variable with name `r` we can write:

In [20]:
q = 7 // 3
r = 7 % 3

Now `q` and `r` contain the quotient and the remainder of the integer division of `7` by `3`as can be seen below:

In [21]:
q

2

In [22]:
r

1

## Lists

In order to present more interesting examples we next show how *Python* supports *lists*.  A list is created using the square brackets 
`[` and `]`.  For example, the empty list, that is the list containing no elements, is written as `[]`.

In [23]:
[]

[]

The list containing the elements `1`, `2`, and `3` is written by seperating the elements with a `,` as shown below:

In [24]:
[1, 2, 3]

[1, 2, 3]

The spaces that I have used in the previous example are optional but recommended.

There are a number of predefined functions that take lists as arguments.  For example, the function `sum` takes a list of numbers and adds these numbers.

In [25]:
sum([1, 2, 3])

6

To create a list containing all numbers starting from a given number $a$ up to but excluding the number $b$ we can use *list comprehension* together with the function `range`.  For example, the list of the first 10 positive natural numbers can be written as:

In [26]:
range(1, 10+1)

range(1, 11)

In [27]:
L = [n for n in range(1, 10+1)]
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The function call `range(a, b)` takes two integers `a` and `b` and returns the sequence of numbers from `a` upto `b-1`.

The general syntax for a list comprehension expression is
$$ [x \quad \texttt{for}\; x \;\texttt{in}\; e]$$
where `for` and `in` are keywords, $x$ is a variable used for iterating while $e$ is an expression that evaluates to a so called *iterable*.  For example, a list is an *iterable* because we can *iterate* over its elements.

We can also combine *list selection* with *list comprehension*.  This is done by using the keyword `if` followed by an expression that evaluates as either `True` of `False` for all elements that are generated by the comprehension expression.  For example, the following expression computes the list of all positive even numbers less or equal than $10$.

In [28]:
E = [n for n in L if n % 2 == 0]
E

[2, 4, 6, 8, 10]

Here, the expression `n % 2 == 0` tests whether the remainder that is left when `n` is divided by `2` is equal to `0`.
Note that we have to use the operator `==` to compare to numbers for equality, since the string `=` is used as the *assignment operator* in *Python*.

In [29]:
[n*n for n in L]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

The *index operator* $[\cdot]$ is a postfix operator that is used to return the element that is stored at 
a given *index* in a list.  For example, If `L` is a list, then `L[0]` returns the first element of `L`.  (Yes, indexing is zero-based in *Python*, so the first element has index `0`.)

In [30]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [31]:
L[0]

1

To change the first element of a list, we can use the *index operator* on the left hand side of an *assignment*:

In [32]:
L[0] = 7
L

[7, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Lists can be *concatenated*  with the operator `+`: 

In [33]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

The function `len` computes the *length* of a list.  The length of a list $L$ is defined as the number of elements of $L$:

In [34]:
len([4, 5, 4])

3

Lists support the functions <tt>max</tt> and <tt>min</tt>.  The expression $\texttt{max}(L)$ computes the maximum of all the elements of the list (or tuple) $L$, while $\texttt{min}(L)$ computes the smallest element of $L$.  These functions also operate on tuples or sets.  

In [35]:
max([1, 2, 3])

3

In [36]:
min([1, 2, 3])

1

In [37]:
T = (1, 2, 3)

In [38]:
T[0]

1

In [39]:
T[0] = 7

TypeError: 'tuple' object does not support item assignment

## Scripts and Functions

Next, we show how it is possible to combine multiple expressions in a *script* and how to create *user defined functions*.

To begin with we present a script that asks the user to input a natural number $n$ and then proceeds to compute the sum of all natural numbers from $1$ upto and including $n$, that is it computes the sum
$$ \sum\limits_{i=1}^n i = 1 + 2 + 3 + \cdots + (n-2) + (n-1) + n. $$
The script contained in the cell below works as follows:
 * The function <tt>input</tt> prompts the user to enter a string.
 * This string is then converted into an integer using the function <tt>int</tt>.
 * Next, the list `L` is created such that 
   $$\texttt{L} = [1, 2, 3,\cdots, (n-2), (n-1), n]. $$  
 * The `print` statement uses the function `sum` to compute the sum of
   all the elements of the List `L`.  The effect of the last argument `sep=''`
   is to prevent `print` from separating its arguments by spaces.

In [40]:
n = input('Type a natural number and press return: ')
n = int(n)
L = [i for i in range(1, n+1)]
print('The sum 1 + 2 + ... + ', n, ' is equal to ', sum(L), '.', sep='')

Type a natural number and press return: 36
The sum 1 + 2 + ... + 36 is equal to 666.


If we input the number $36$, which happens to be equal to $6^2$, then we discover the following remarkable identity:
$$ \sum\limits_{i=1}^{6^2} i = 666. $$

The next example shows how *functions* can be defined in *Python*.  The function $\texttt{sum}(n)$ is supposed 
to compute the sum of all the numbers in the set $\{1, \cdots, n\}$.  Therefore, we have
$$\texttt{sum}(n) = \sum\limits_{i=1}^n i. $$  
The function `sum` is defined *recursively*.  The recursive implementation of the function `sum` can best by understood if we observe that it satisfies the following two equations:
 * $\texttt{sum}(0) = 0$, 
 * $\texttt{sum}(n) = \texttt{sum}(n-1) + n \quad$  provided that $n > 0$.

The keyword `def` is used to signal that we define a function.

In [3]:
def sum(n):
    if n == 0:
        return 0
    return sum(n-1) + n

Lets test this function.

In [4]:
sum(10)

55

Let us discuss the implementation of the function `sum` line by line:
  1. The keyword `def` starts the definition of the function. 
     It is followed by the name of the function that is defined.  The name is followed by the list of the parameters of the 
     function.  This list is enclosed in parentheses. If there had been more than one parameter, the parameters would have 
     been separated by commas.  Finally, there needs to be a colon at the end of the first line.
  2. The body of the function is *indented*.  **Contrary** to most other programming languages, 
     <u>Python is space sensitive</u>. 
     The first statement of the body is a *conditional statement*, which starts with the keyword
     `if`.  The keyword is followed by a test.  In this case we test whether the variable $n$ 
     is equal to the number $0$.  Note that this test is followed by a colon `:`.
  3. The next line contains a `return` statement.  Note that this statement is again indented.
     All statements indented by the same amount that follow an `if`-statement are considered as
     the *body* of the `if`-statement.  In this case the body contains only a single statement.
  4. The last line of the function definition contains the recursive invocation of the function `sum`
     that computes the value `sum(n)` by reducing it to the value `sum(n-1)`.

Using the function `sum`, we can compute the sum $\sum\limits_{i=1}^n i$ as follows:

In [ ]:
n     = int(input("Enter a natural number: "))
total = sum(n)
if n > 2:
    print("0 + 1 + 2 + ... + ", n, " = ", total, sep='')
else: 
    print(total)

## Boolean Values and Boolean Operators

In *Python*, the *truth values*, also known as *Boolean values*, are written as <tt>True</tt> and <tt>False</tt>. 

In [45]:
True

True

In [46]:
False

False

The following function is needed for pretty-printing.  It assumes that the argument <tt>val</tt> is a truth value.  This truth value is then turned into a string that has a size of exactly 5 characters.

In [47]:
def toStr(val):
    if val:
        return 'True '
    return 'False'

These values can be combined using the *Boolean operators* $\wedge$, $\vee$, and $\neg$.  In *Python*, these operators are denoted as `and`, `or`, and `not`.  The following table shows how the operator `and` is defined:

In [48]:
B = [True, False]
for x in B:
    for y in B:
        print(toStr(x), 'and', toStr(y), '=', x and y)

True  and True  = True
True  and False = False
False and True  = False
False and False = False


The *disjunction* of two Boolean values is only *False* if both values are *False*.  In *Python*, the disjunction operator is written as `or`:

In [49]:
for x in B:
    for y in B:
        print(toStr(x), 'or', toStr(y), '=', x or y)

True  or True  = True
True  or False = True
False or True  = True
False or False = False


Finally, the <em style="color:blue;">negation</em> operator `not` works as expected:

In [ ]:
for x in B:
    print('not', toStr(x), '=', not x)

Boolean values are created by comparing numbers using the comparison operators
`==`, `!=`, `<`, `>`, `<=`, and `>=`:
 * $a\;\texttt{==}\;b$ is true iff $a$ is equal to $b$.
 * $a\;\texttt{!=}\;b$ is true iff $a$ is different from $b$.
 * $a\;\texttt{<}\;b$ is true iff $a$ is less than $b$.
 * $a\;\texttt{<=}\;b$ is true iff $a$ is less than or equal to $b$.
 * $a\;\texttt{>=}\;b$ is true iff $a$ is bigger than or equal to $b$.
 * $a\;\texttt{>}\;b$ is true iff $a$ is bigger than $b$.

In [ ]:
1 == 2

In [ ]:
1 != 2

In [ ]:
1 < 2

In [ ]:
1 <= 2

In [ ]:
1 > 2

In [ ]:
1 >= 2

Comparison operators can be <em style="color:blue;">chained</em> as shown in the following example:

In [ ]:
1 < 2 < 3

*Python* supports the <em style="color:blue;">universal quantifier</em> $\forall$.  If $L$ is a list of Boolean values, then we can check whether all elements of $L$ are <tt>True</tt> by writing
$$ \texttt{all}(L). $$
For example, to check whether all elements of a list $L$ are even we can write the following:

In [ ]:
L = [2, 4, 6, 8]
all([x % 2 == 0 for x in L])

*Python* also supports the <em style="color:blue;">existential quantifier</em> $\exists$.  If $L$ is a list of Boolean values, the expression
$$ \texttt{any}(L) $$
is true iff there exists an element $x \in L$ such that $x$ is true.

In [ ]:
L = [n for n in range(1, 9+1)]
any([n ** 2 > 2 ** n for n in L])

## Control Structures

First of all, *Python* supports *branching* via the keywords `if`, `elif`, and `else`.  The following example is taken from the *Python* tutorial at [https://python.org](https://docs.python.org/3/tutorial/controlflow.html):

In [ ]:
s = input("Please enter an integer: ")
x = int(s)
if x < 0:
    print('The number is negative!')
elif x == 0:
    print('The number is zero.')
elif x == 1:
    print("It's a one.")
else:
    print("It's more than one.")

*Loops* can be created with the keyword `for`.  They can be used to iterate over lists.    
The syntax of a `for`-loop is:
```
   for x in L:
       S1
       ...
       Sn
```
Here, `x` is the name of a variable that is used to iterate over the elements of the list `L`.  The statements
`S1`, $\cdots$, `Sn` make up the *body* of the loop.  These statements are executed for every element of the list `L`.

The next examples shows a simple loop that prints all the elements from the list `L`:

In [ ]:
for x in L:
    print(x)

Another way to write a *loop* is to use the keyword `while` as in the following example:

In [ ]:
x = 1
while x < 10:
    print(x)
    x = x + 1

The general syntax of a `while`-loop is as follows:
```
    while e:
        S1
        ...
        Sn
```
Here, `while` is the keyword starting the `while`-loop, while `e` is an expression that contains some variable `x` which is presumably updated in the statements `S1`, $\cdots$, `Sn`.  These statements are executed as long as the expression `e` is `True`.

The following program computes the prime numbers according to an
[algorithm given by Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes).
 1. We set $n$ equal to 100 as we want to compute the set all prime numbers less or equal that 100.
 2. `primes` is the list of numbers from 0 upto $n$, i.e. we have initially
    $$ \texttt{primes} = [0,1,2,\cdots,n] $$
    Therefore, we have initially
    $$ \texttt{primes}[i] = i \quad \mbox{for all $i \in \{0,1,\cdots,n\}$.} $$
    The idea is to set $\texttt{primes}[i]$ to zero iff $i$ is a proper product of two numbers.
 3. To this end we iterate over all $i$ and $j$ from the list $[2,\cdots,n]$
    and set the product $\texttt{primes}[i\cdot j]$ to zero.  
    This is achieved by the two `for` loops in line 4 and line 5 below.

    Note that we have to check that the product $i * j$ is not bigger than $n$ 
    for otherwise we would get an *out of range error* when trying to assign $\texttt{primes}[i*j]$.     
    
 4. After the iteration, all non-prime elements greater than one of the list primes have been set to zero.
 5. Finally, we compute the list of all prime numbers by collecting those elements from the list `primes` 
    that have not been set to $0$.

In [ ]:
n         = 100
primes    = [i for i in range(0, n+1)]
primes[1] = 0
for i in range(2, n+1):
    for j in range(2, n+1):
        if i * j <= n:
            primes[i * j] = 0
print(primes)
print([i for i in range(2, n+1) if primes[i] != 0])

The algorithm given above can be improved by using the following observations:
 1. If a number $x$ can be written as a product $a \cdot b$, then at least one of the numbers 
    $a$ or $b$ has to be less than $\sqrt{x}$.  Therefore, the `for` loop in line 5 below 
    iterates as long as $i \leq \sqrt{x}$.  The function `ceil` is needed to cast the square 
    root of $x$ to a natural number.  In order to use the functions `sqrt` and `ceil` we have 
    to import them from the module `math`.  This is done in line 1 of the program shown below. 
 2. When we iterate over $j$ in the inner loop, it is sufficient if we start with $j = i$ 
    since all products of the form $i \cdot j$ where $j < i$ have already been eliminated at the time 
    when the multiples of $i$ had been eliminated.
 3. If $\texttt{primes}[i] = 0$, then $i$ is not a prime and hence it has to be a product of two 
    numbers $a$ and $b$ both of which are smaller than $i$.  However, since all the multiples of 
    $a$ and $b$ have already been eliminated, there is no point in eliminating the multiples of 
    $i$ since these are also multiples of both $a$ and $b$ and hence they have already been eliminated.    
    Therefore, if $\texttt{primes}[i] = 0$ we can immediately jump to the next value of $i$.  
    This is achieved by the *continue* statement in line 8 below. 

The program shown below is easily capable of computing all prime numbers less than a million.
On my desktop computer, which is a 2017 iMac with a Quad-Core Intel i5 processor, this takes less than a second.

In [ ]:
%%time
import math

n = 1_000_000
primes = list(range(n+1))
for i in range(2, math.ceil(math.sqrt(n))):
    if primes[i] == 0:
        continue
    j = i
    while i * j <= n:
        primes[i * j] = 0
        j += 1
P = [i for i in range(2, n+1) if primes[i] != 0]
print(P)

## Numerical Functions

*Python* provides all of the mathematical functions that you have learned about at school.  A detailed listing of these functions can be found at 
[https://docs.python.org/3.6/library/math.html](https://docs.python.org/3.6/library/math.html).  We just show the most important functions and constants.  In order to make the module `math` available, we use 
the following `import` statement: 

In [ ]:
import math

The mathematical constant [Pi](https://en.wikipedia.org/wiki/Pi), which in mathematics is written as $\pi$, is available as `math.pi`.

In [ ]:
math.pi

The <a href="https://en.wikipedia.org/wiki/Sine">sine</a> function is called as follows:

In [ ]:
math.sin(math.pi/6)

The <a href="https://en.wikipedia.org/wiki/Trigonometric_functions#cosine">cosine</a> function is called as follows:

In [ ]:
math.cos(0.0)

The tangent function is called as follows:

In [ ]:
math.tan(math.pi/4)

The *arc sine*, *arc cosine*, and *arc tangent* are called by prefixing the character `'a'` to the name of the function as seen below:

In [ ]:
math.asin(1.0)

In [ ]:
math.acos(1.0)

In [ ]:
math.atan(1.0)

<a href="https://en.wikipedia.org/wiki/E_(mathematical_constant)">Euler's number $e$</a> is stored as the constant `math.e`:

In [ ]:
math.e

The exponential function $\mathrm{exp}(x) := e^x$ is computed as follows:

In [ ]:
math.exp(1)

The natural logarithm $\ln(x)$, which is defined as the inverse of the function $\exp(x)$, is called `log` (instead of `ln`):

In [ ]:
math.log(math.e * math.e)

The square root $\sqrt{x}$ of a number $x$ is computed using the function `sqrt`:

In [ ]:
math.sqrt(2)

The <em style="color:blue;">flooring function</em> $\texttt{floor}(x)$ truncates a floating point number $x$ down to the biggest integer number less or equal to $x$:
$$ \texttt{floor}(x) = \max(\{ n \in \mathbb{Z} \mid n \leq x \} $$

In [ ]:
math.floor(1.999)

The <em style="color:blue;">ceiling function</em> $\texttt{ceil}(x)$ rounds a floating point number $x$ up to the next  integer number bigger or equal to $x$:
$$ \texttt{ceil}(x) = \min(\{ n \in \mathbb{Z} \mid x \leq n \} $$

In [ ]:
math.ceil(1.001)

The function `round` rounds its input to the nearest integer.  For an integer number $n$, the floating point number $n.5$ is rounded to $n+1$.

In [ ]:
round(1.5), round(1.39), round(1.51)

The function `abs` computes the absolute value.  Note that this function is not part of the math library but rather is a predefined function.  Therefore the name `abs` is  not prefixed with the package name `math`.

In [ ]:
abs(-1)

## The Help System

Typing a single question mark <tt>'?'</tt> starts the help system of the *Jupyter* notebook.

In [ ]:
?

If the name of a module is followed by a question mark, a description of the module is printed.

In [ ]:
math?

This also works for functions defined in a module.

In [ ]:
math.sin?

The question mark operator only works inside a <em style="color:blue;">Jupyter notebook</em>.  

Furthermore, there is the function `help`, which is part of *Python*.

In [ ]:
help(math)

In [ ]:
help(math.sin)

In [ ]:
help(dir)

We can use the function <tt>dir()</tt> to print the names of the variables that have been defined.

In [ ]:
dir()

The names of the form $\textrm{_i}n$ where $n$ is a number refer to the *input* of the $n^{\textrm{th}}$ cell of this notebook.  Let us check the input of the $55^{\textrm{th}}$ cell of this notebook.

In [ ]:
_i21

The names of the form $\textrm{_}n$ where $n$ is a number refer to the *output* produced by the $n^{\textrm{th}}$ cell of this notebook.  

In [ ]:
_21

In [ ]:
2 * 3

Inside a *Jupyter* notebook, the variable `_` refers to the value of the last expression that has been executed.

In [ ]:
_

The <em style="color:blue;">magic</em> command <tt>%quickref</tt> prints an overview of the so called 
<em style="color:blue;">magic commands</em> that are available in <em style="color:blue;">Jupyter notebooks</em>.

In [ ]:
%quickref

We can use the command `ls` to list the files in the current directory.

In [ ]:
ls -al

Prefixing a shell command with a `!` executes this command in a shell.  On the Windows operating system, the system command to list the files in the current directory is called `dir`, while on Linux and MacOS, the corresponding command is known as `ls`.

In [ ]:
!ls

In [ ]:
!dir